# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := walkers test

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

walkers: 
	@echo "==== Building walkers ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f walkers.make

test: 
	@echo "==== Building test ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f test.make

clean:
	@${MAKE} --no-print-directory -C . -f walkers.make clean
	@${MAKE} --no-print-directory -C . -f test.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   walkers"
	@echo "   test"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
